services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MoskvinDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MoskvinDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_api
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MoskvinDb;Username=postgres;Password=postgres
      - Seq__ServerUrl=http://seq:80
  
  seq:
    image: datalust/seq:latest
    container_name: seq_logs
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    ports:
      - "5341:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_web
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: